name: Metrics
on:
  # Schedule updates once a day (at midnight)
  schedule: [{cron: "0 0 * * *"}]
  # (Optional) Allow manual refresh from the Actions tab
  workflow_dispatch:
  # (Optional) Run on every push to the main branch
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: DashPriyabrata
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: Asia/Singapore
          
          # Lines of Code Plugin
          plugin_lines: yes
          plugin_lines_sections: base
          plugin_lines_delay: 30
          
          # DISABLE EVERYTHING ELSE (to keep it clean)
          plugin_notable: no
          plugin_community: no
          plugin_languages: no
